Refactoring/fields
azeem/webvs pull request #40
Opened 2018-05-27 23:15 UTC by grandchild

The commit messages are verbose and should say it all.

2018-06-03 22:15 UTC, grandchild commented
The matching branch on the converter is [grandchild/AVS-File-Decoder/refactoring/fields](https://github.com/grandchild/AVS-File-Decoder/tree/refactoring/fields).

2018-06-25 02:43 UTC, azeem requested changes

2018-06-25 02:43 UTC, azeem commented on src/webgl/ShaderProgram.ts
> +        // [BlendMode.EVERY_OTHER_LINE]: "mix(color, getSrcColor(), float(uint(v_position.y * u_resolution.y) & 1u))",
Did you mean to un-comment these? If not, let's create tickets for these instead of leaving them commented out in the code.

2018-06-25 02:43 UTC, azeem commented on test/func/trans/ColorMap.test.ts
> +                key: "RED", maps, output: "FIFTY_FIFTY",
This breaks the func test. Should be `blendMode: "FIFTY_FIFTY"`

2018-06-25 16:02 UTC, grandchild commented
Rebased onto master and fixed the requested changes (and linting errors, which I wasn't aware of. thanks circleci ;P)

2018-06-25 17:43 UTC, merged

2018-06-25 17:43 UTC, azeem commented
Thanks!